name: Mirror to Codeberg

on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        run: |
          git remote add codeberg "https://HassanAlsheikh:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/AlsheikhMedia/${{ github.event.repository.name }}.git"
          git push --mirror codeberg
